### PR TITLE
Add function check_user_rights to check for API privilege errors

### LINKED ISSUE #23: [FEATURE] Missing Instrument Detection
# Feature Request Description
When a user does not have the appropriate privileges to specific instruments, it can causes an error. This happened recently where new instruments were created in a database but the user API was not updated to grant access, causing a disparity between expected instruments in the metadata and exported data from the database.

This should throw a warning when expected instruments are not found in the database export.

# Proposed Solution
This should throw a warning when expected instruments are not found in the database export.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

### PR DESCRIPTION
**Pull request by rsh52**
# Description
This PR introduces a new `/R` file, `checks.R` (open to name change if desired), which will host functions that supply database checks during REDCap extraction and processing.

The function introduced here is `check_user_rights` (since `checkmate::check_access` is taken), to provide users with a warning message detailing the expected form name and its associated field names.

# Proposed Changes 
List changes below in bullet format:

- Add `R/checks.R` file to directory
- Introduce `check_user_rights` function, add conditional application to `read_redcap_tidy`
- Supply test for `check_user_rights` which doesn't rely on API calls or RDS loading
- Updated `clean_redcap` test to suppress warning since check happens before `clean_redcap` calls

**Screenshots**
 I created two test instruments with fields that I denied myself access to to trial the output shown below:

```
1: Form name {api_no_access} detected in metadata but not found in the database export. Check your user API privileges. The following variables have been removed from the output: api_text 
2: Form name {api_no_access_2} detected in metadata but not found in the database export. Check your user API privileges. The following variables have been removed from the output: api_text_2, api_text_3, api_text_4 
```

### Issue Addressed
**Closes #23**

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [x] New/revised functions have associated tests
- [x] New/revised functions use appropriate naming conventions
- [x] New/revised functions don't repeat code
- [x] Code changes are less than **250** lines total
- [x] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] The appropriate reviewer is assigned to the PR
- [x] The appropriate developers are assigned to the PR

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [ ] I checked that new files follow naming conventions and are in the right place
- [ ] I checked that documentation is complete, clear, and without typos
- [ ] I added/edited comments to explain "why" not "how"
- [ ] I checked that all new variable and function names follow naming conventions
- [ ] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [ ] I checked that new tests address important edge cases

### CODE REVIEW

**Comment by skadauke** [comment]
Hey, I don't think the API for `check_user_rights` makes sense. If the purpose of the function is to check something it really shouldn't return anything. Check functions should warn or fail or be silent, they shouldn't do any data transformations.

**Comment by rsh52** [comment]
> Hey, I don't think the API for `check_user_rights` makes sense. If the purpose of the function is to check something it really shouldn't return anything. Check functions should warn or fail or be silent, they shouldn't do any data transformations.

Updated to shift all transformation out of the API and into `read_redcap_tidy` if condition met, `check_user_rights` now only returns warning messages. Updated applicable tests as well, though now it only checks for a warning trigger.

**Comment by rsh52** [comment]
Also once we merge this it should take care of the current `main` test failures related to subsets that don't exist :)

**Review by skadauke — APPROVED** [review]
This looks great to me! I hope my edits in `checks.R` didn't break things.

**Comment by rsh52** [comment]
> This looks great to me! I hope my edits in `checks.R` didn't break things.

There was a missing quotation, fixed and all good. Will merge now!

**Pull request merged**
