### PR TITLE
Remove looping over longitudinal events in distill_*_table_long

### PR DESCRIPTION
**Pull request by ezraporter**
# Description
This PR addresses the first and largest bottleneck described in https://github.com/CHOP-CGTDataOps/REDCapTidieR/issues/48#issuecomment-1285717234. Currently for each form we are looping over longitudinal events and sequentially filtering the data to remove events that aren't mapped to the form. A faster solution is to aggregate all the event mappings for the form upfront and filter to only the events mapped to the form. (Would like to get Rich's thoughts to make sure I'm understanding the subtleties of longitudinal redcaps!)

I also modified the `link_arms()` function to return a `tibble` in a more standard format. That has two benefits:
1. Makes it slightly easier to grab all the events associated with a form
2. Returns form-event mappings in a friendlier format that we can use as metadata for #16 

# Proposed Changes 
List changes below in bullet format:

- Refactor `link_arms()` to return a more standard event-form `tibble`
- Refactor `distill_*_table_long()` functions to avoid looping over longitudinal events

# Additional Info

1. Tests are currently failing because we need to rerun `inst/testdata/create_test_data.R`. I'm missing 2 redcap API keys to do that:
```r
classic_norepeat_token <- Sys.getenv("REDCAPTIDIER_CLASSIC_NOREPEAT_API")
longitudinal_norepeat_token <- Sys.getenv("REDCAPTIDIER_LONGITUDINAL_NOREPEAT_API")
```

2. I had to make similar changes to both `distill_repeat_table_long()` and `distill_nonrepeat_table_long()`. Should we consider combining them into a single function? It looks like there's non-trivial code duplication.

3. This shaved about 4 seconds off our run time with the prodigy db:

```r
devtools::load_all()
library(microbenchmark)
library(profvis)

redcap_uri <- Sys.getenv("REDCAP_URI")
redcap_token <- Sys.getenv("PRODIGY_REDCAP_API")

microbenchmark(read_redcap_tidy(redcap_uri, redcap_token), times = 10)

#> Unit: seconds
#>                                       expr      min       lq     mean   median       uq      max neval
#> read_redcap_tidy(redcap_uri, redcap_token) 9.812751 10.34588 10.61901 10.55411 11.03919 11.44642    10
```

```r
profvis::profvis(read_redcap_tidy(redcap_uri, redcap_token), simplify = FALSE)
```
Screen Shot 2022-10-21 at 12 51 03 PM

We're actually spending less time here than in the checkbox updating now.

### Issue Addressed
Relates to #48 

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [x] New/revised functions have associated tests
- [x] New tests that make API calls use `httptest::with_mock_api` and any new mocks were added to `tests/testthat/fixtures/create_httptest_mocks.R`
- [x] New/revised functions use appropriate naming conventions
- [x] New/revised functions don't repeat code
- [x] Code changes are less than **250** lines total
- [x] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] The appropriate reviewer is assigned to the PR
- [x] The appropriate developers are assigned to the PR

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [x] I checked that new files follow naming conventions and are in the right place
- [x] I checked that documentation is complete, clear, and without typos
- [x] I added/edited comments to explain "why" not "how"
- [x] I checked that all new variable and function names follow naming conventions
- [x] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [x] I checked that new tests address important edge cases

### CODE REVIEW

**Comment by skadauke** [comment]
This is great! Looks like we already decreased runtime by half??

I had actually discussed with @rsh52 previously to refactor `link_arms()` to return a tibble. At the time we decided to leave it alone because it was working. But I agree, this is a good opportunity to deal with some tech debt. 

I also agree with the idea of combining `distill_repeat_table_long` and `distill_nonrepeat_table_long` if it's easy to do. Would probably prioritize this lower than any of the outstanding bug reports and feature requests however. I would say, if you think you can tackle this as part of this PR with less than 3 hours of work, go for it.

@rsh52, can you provide all REDCap API keys to Ezra so we can get the tests to pass?

**Review by rsh52 — CHANGES_REQUESTED** [review]
> @rsh52, can you provide all REDCap API keys to Ezra so we can get the tests to pass?

@ezraporter I looked through all of the REDCap databases, you currently have API privilege access to all of them but it doesn't seem like a token has been generated for "**[REDCapTidier Test - Classic No Repeat](https://redcap.chop.edu/redcap_v12.5.8/UserRights/index.php?pid=53972)**" and "**[REDCapTidieR Test - Longitudinal No Repeats](https://redcap.chop.edu/redcap_v12.5.8/UserRights/index.php?pid=53974)**". I can give you mine if necessary, but prefer if we keep API keys to our own management. Let me know if this still doesn't work and I'll cease my grumbling.

> I had to make similar changes to both distill_repeat_table_long() and distill_nonrepeat_table_long(). Should we consider combining them into a single function? It looks like there's non-trivial code duplication.

If we can do it, let's! Good time to consolidate. My guess is we totally can, but at the time of writing these functions we wanted to keep their responsibilities separate until we had a clearer picture of what we wanted them to do.

Skimmed through the changes a bit this morning and so far really liking the improvements, much cleaner and easier to read. Also realizing a test was never written for `link_arms`, should write one especially now that it has a more manageable output. We should write that before merging, then when all the checks pass this should be good to go! Fantastic work Ezra 🎉

**Comment by ezraporter** [comment]
> If we can do it, let's! Good time to consolidate. My guess is we totally can, but at the time of writing these functions we wanted to keep their responsibilities separate until we had a clearer picture of what we wanted them to do.

Actually any objections to making this a separate issue and handling it in a new branch? I'm hesitant to make the diff on this one any larger.

**Comment by rsh52** [comment]
> > If we can do it, let's! Good time to consolidate. My guess is we totally can, but at the time of writing these functions we wanted to keep their responsibilities separate until we had a clearer picture of what we wanted them to do.
> 
> Actually any objections to making this a separate issue and handling it in a new branch? I'm hesitant to make the diff on this one any larger.

Yes, definitely. Better to get these changes finalized and implemented then move on to the next ones.

**Comment by ezraporter** [comment]
Should be good for review once the checks finish. I had to move a couple things around to add the `link_arms()` test since it's an API calling function so should use `httptest`.

**Review by skadauke — APPROVED** [review]
LGTM!

**Review by rsh52 — APPROVED** [review]
Ditto, thank you for writing up the test and updating the mocks. Good to merge!

**Pull request merged**
